### PR TITLE
update Print() class to support printf() formatted printing

### PR DESCRIPTION
**Pull request by vortigont**
a recent Print() class implementation from esp32 core that allows to use printf() formatted output

### CODE REVIEW

**Comment by marcmerlin** [comment]
Thanks, happy to update the very old arduino core that got inherited there.
Could I ask you to send a diff that doesn't change whitespace so that I can see what's being changed? Right now the entire file is replaced, so I can't see anything. I actually prefer your spacing for what it's worth, but I'd rather keep the original upstream format so that it's easier to diff.
(yes, it would be cool if github had a diff that ignores whitespace, but didn't find one)

**Comment by vortigont** [comment]
Ugh... those line endings are killing me :( Spend an hour in attempt to make it right way.
The issue is that in original repo (i.e. yours also) all files are with windows line ends already, and usually it should be linux-like in repo and converted to client's OS preferred on checkout. I work on Linux and it tries hard to do it "proper" way :)
I'm able to see a real diff in my working dir with `git diff --ignore-cr-at-eol`, but on commit it includes all ending changes.
OK, let me try to make it a nice way and get back with updated PR.

Thanks for your work on this!

**Comment by marcmerlin** [comment]
Sorry for the hassle, and yeah I'm also on linux so I know what you mean.
My repo came from the original guy who wrote this, who in turn must have taken the arduino files from arduino and checked them as is. It would be good if github could do a diff without worrying about this (actually it may), although I think I noticed that your diff also had different indentation (2 vs 4 spaces), which will make the diff unhappy, and this may be the only problem

**Comment by vortigont** [comment]
OK, one more try :)
So I've just cloned the repo with as-is option and rebased it. Working dir looks ugly on Linux, but whatever... I can live with two repos :)))
For indentation I just copied whole file from esp32's framework as-is, so it mat come from their end also.
Just had to add `#include <stdarg.h>` to make gcc happy.
Is that would be OK this way, or you prefer to revert the indentation to the old style?

**Comment by marcmerlin** [comment]
So the problem is still that
https://github.com/marcmerlin/ArduinoOnPc-FastLED-GFX-LEDMatrix/compare/e0478b9f8533d3eb38b80538dba6769d73d87b51..17787cdd267697423c8649a019e8bd4dbc3480ca
is not a diff, but a full file replacement.
Is there anything you can do to get an actual diff with just what changed?

I don't agree or like the original indent, but I inherited it, and rule #1 is to keep whatever was there to get useful diffs

**Comment by marcmerlin** [comment]
actually, sorry, have a look at 
https://github.com/marcmerlin/ArduinoOnPc-FastLED-GFX-LEDMatrix/pull/10/files
this is the diff I'm actually reviewing, and it has still lots of whitespace changes
That said it's not just a patch, this is pretty much a new upstream file, correct?

If so, I'm not going to ask you to reformat an upstream file to match the old one. If you can certify "this is a newer unmodified upstream, and I tested it to be compatible and not to break the interface of the previous file", I'm willing to submit as is, even if the diff is not really reviewable

**Comment by marcmerlin** [comment]
and, sorry, doing 3 other things, so I missed the fact that you're indeed substituting the ESP32 copy which is obviously very different.
I do like the change, because yes, printf is better for sure. Can you please do some basic testing on the functions being replaced, to make sure they still work (you can't test everything, but at least some basic testing). 
If you give me thumbs up, I'll blind approve this on faith since I don't have the time to fully review and test this, but indeed I do like the change you're proposing and the better print from ESP32 core lib

**Comment by marcmerlin** [comment]
and as one last update, since I won't be able to review this just by sight on github (too much of a change), don't worry too much if the indents or whitespace aren't perfect, but indeed you can do a local whitespace ignoring diff on your side with git diff to do a self review

**Comment by vortigont** [comment]
yes, sorry if I was not clear enough, I've just replaced Print.h and cpp with esp32's from a stable core version. So that's where the indent's are all different. Was not me who introduced it :)))  Actually I was trying to get same from esp866 but it includes lot's of PGM' related wrappers and it does not fit well at all, so I've addressed to esp32's. It's more clean and close to old one, not sure were it came from. I've tested it with some basic types (int's, unsigned, floats, char*) works pretty good with console output.
OK, let me go through it a bit more closely if I can find any potential problem or esp specific cases.
Will let you know.
Cheers!

**Comment by marcmerlin** [comment]
any luck? should I look more, or are you still working on it?

**Comment by vortigont** [comment]
ugh, yeah, still on it, was out for the weekend actually :)
will check this out, not forgotten :)

**Comment by vortigont** [comment]
OK, I've checked the changes more closely. Looks like no ESP specifics were used anywhere, and no methods were obsoleted. For the new features there is an `printf` which uses standard lib's vsnprintf for manipulating strings, so should be all OK. Another one is printing `struct tm*` for time formatiing, which is also using standard `strftime`.
Tested it with various combination of numeric format, all good. Should be no problem replacing the old one I believe.

**Comment by marcmerlin** [comment]
Thank you so much for the contribution and doing the review to make sure it doesn't break anything

**Comment by marcmerlin** [comment]
Ok, now I get to ask what project, you are using this code for, I'm curious :)
(mostly asking because I think a lot more people should use it for quicker prototyping and debugging, so I'm happy at least a few people find it)

**Comment by vortigont** [comment]
sure, I'm using to do some dirty testing for various LED effects while prototyping for [FireLamp](https://github.com/vortigont/FireLamp_JeeUI) project. Sorry, it's mostly in Russian and lacks some nice screenshots though ) It's another idea of a so-called "Gywer lamp".
So I need a tool to check/estimate how various effects will look like without doing multiple reflashing on a real board.
[Soulmate's](https://editor.soulmatelights.com/) editor lacks most of C++ 11 and STD lib, [Wokwi](https://wokwi.com/) can run emulated LED matrix only on AVR boards which has pretty low memory.
So I ended up with your project remembering I came across it while was working on [ESP32-HUB75-MatrixPanel-DMA](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/) some time ago.
Have some question regarding SDL backend, by the way. Will open separate issue for this if you do not mind.

**Comment by marcmerlin** [comment]
Thanks for the answer, I was curious indeed :)
I tested your patch with my code and it all works fine, thanks.
As for SDL, that is the code I didn't write and inherited from https://github.com/ChrisMicro/ArduinoOnPc
Hopefully you can hear back there and feel free to mention me in the bug, I'm curious about what you found and the reply from @chrismicro 
Ah, I just saw the other issue you filed, I'll reply there.

**Pull request merged**
